name: decanat_progect
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.11
  youtube_player_flutter: ^9.1.2
  curved_navigation_bar: ^1.0.6
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logotiti.mp4